sonar.projectKey=panda-jump
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/reports/**,assets/**
sonar.coverage.exclusions=src/main.ts,src/scenes/**
sonar.javascript.lcov.reportPaths=.marestail/ts-coverage/lcov.info
sonar.sourceEncoding=UTF-8
